### PR TITLE
Add --sanity option and fill in expectaions for Intel X710

### PR DESCRIPTION
**Pull request by ol-andrewr**
Update tests to produce sensible verdicts and take more limitations into account.

Example log:
https://ts-factory.io/bublik/v2/runs/221577

### CODE REVIEW

**Comment by ol-andrewr** [comment]
QEMU virtio-net testing logs:
https://ts-factory.io/bublik/v2/runs/229087

**Comment by ol-andrewr** [comment]
It is a TRC key2html. So, it has never worked for HTML logs.

It is good that substitution works for you in trc-brief.html. It is the expected behaviour.

It is expected that my logs have no substitution, unfortunately. I have no corresponding config locally. I'll fix it.

**Comment by ol-andrewr** [comment]
I have one more PR waiting in a queue. I just don't want to submit it since it overlaps with this one and spoil your efforts here. Please, move forward.

**Comment by okt-denispr** [comment]
Thanks Andrew! I've pushed your commits with proper review trailers.
I've closed this PR, as all changes are already in the repo but GitHub web interface can't rebase it and merge.

**Pull request closed without merging**
